import {
  PROJECT,
  REON,
  SLASH,
  STRUCTURES,
  MACHINE,
  MEESEEKS_BOX,
  SHRUBS,
} from "./directories";
import {
  STRUCTURES_CSV,
} from "./files";

export const APPLICATION = MACHINE + SLASH + MEESEEKS_BOX;

export const APPLICATION_STRUCTURES = APPLICATION + SLASH + STRUCTURES;
export const APPLICATION_REON = APPLICATION + SLASH + REON;

export const PROJECT_STRUCTURES = PROJECT + SLASH + STRUCTURES;
export const PROJECT_REON = PROJECT + SLASH + REON;
export const PROJECT_REON_SHRUBS = PROJECT + SLASH + REON + SLASH + SHRUBS;

export const APPLICATION_STRUCTURES_CSV = APPLICATION_STRUCTURES + SLASH + STRUCTURES_CSV;

export const PROJECT_STRUCTURES_CSV = PROJECT_STRUCTURES + SLASH + STRUCTURES_CSV;
